# Generated by Django 2.2 on 2021-11-28 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffPermissions',
            new_name='StaffPermission',
        ),
    ]
