# Generated by Django 2.2 on 2021-11-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20211128_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
