# Generated by Django 2.2 on 2022-02-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20220222_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_app_user',
            field=models.BooleanField(default=True),
        ),
    ]
