# Generated by Django 2.2 on 2022-02-22 14:38

from django.db import migrations, models
import places.utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_orderitem_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customization',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='customizationoption',
            name='option',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_id',
            field=models.CharField(default=places.utils.helpers.generate_invoice_id, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
