# Generated by Django 2.2 on 2022-02-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20220222_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='invoice_id',
            new_name='invoice',
        ),
    ]
