# Generated by Django 2.2 on 2022-02-22 14:56

from django.db import migrations, models
import places.utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20220222_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.CharField(blank=True, default=places.utils.helpers.generate_invoice_id, max_length=12, null=True, unique=True),
        ),
    ]
